### ISSUE TITLE
Getting error in cloud function log

### ISSUE THREAD

**Issue by jayaram250** [harsh4870/cloud-function-scale-gke#2]
Hi Thanks for your script,

 I installed it as a google cloud function , when I trigger it with a google cloud schedule it fails with below error,

Error: 5 NOT_FOUND: Not found: projects/test-trial/zones/europe-west2-a/clusters/test-cluster. at Object.callErrorFromStatus (/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:31:26) at Object.onReceiveStatus (/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client.js:179:52) at Object.onReceiveStatus (/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141) at Object.onReceiveStatus (/workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181) at /workspace/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78 at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Cluster information:**
cloud function node version: 16
GKE cluster version: 1.25.6-gke.1000
GKE node version-1.25.6-gke.200
clustername: test-cluster
projectname: test-trial

everything is verified but i'm getting the above error,please check once.

**Comment by harsh4870** [comment]
Can you check the region and zone of your cluster once.

**Comment by jayaram250** [comment]
Verified and we are using zone in scheduler, still getting same error.
Region : europe-west2 
Zone : europe-west2-a
